id: P004165
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:57:39.935033
source_metadata:
  id: bdr:W1KG3386
  title: འབྲི་རྒྱུད་རབ་བརྟན་དགོན་གྱི་ལོ་རྒྱུས།
  author: ''
  volumes:
    c60ff0055c1344afa3622042ce1abf07:
      image_group_id: I1KG3975
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
