id: P004165
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3386
  title: འབྲི་རྒྱུད་རབ་བརྟན་དགོན་གྱི་ལོ་རྒྱུས།
  author: ''
  volumes:
    c60ff0055c1344afa3622042ce1abf07:
      image_group_id: I1KG3975
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
