id: IF4771E70
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:32:13+00:00'
last_modified: '2022-06-07T20:44:17.318149+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3386
  title: འབྲི་རྒྱུད་རབ་བརྟན་དགོན་གྱི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3B0D:
      image_group_id: I1KG3975
      title: ''
      total_pages: 178
      order: 1
      base_file: 3B0D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
